name: Node.js CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}


on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']


jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [18.x]


    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'


      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: yarn cy:run
          start: yarn start
        env:
          CI: false
          REACT_APP_API_WEATHER_URL: https://express-api-proxy-example.vercel.app
          REACT_APP_API_KEY_WEATHER: 9v7n5SUsjmhs4ZpmHw9lveA0cElmIiN9
          REACT_APP_ACCESS_KEY_IMAGE_API: W4ZguEAZZKuP2ek_sqUb_vqV-6FvzSHvWKdyKSySXe8


      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
